import { IsEmail, IsOptional, IsString, Length, Matches } from 'class-validator';

/**
 * Body for `POST /api/internal/web-auth/register`.
 *
 * Identity model:
 *   - The canonical `reiwa_id` (`User.id`) is generated by Prisma. The
 *     caller never supplies it.
 *   - `telegramIdToLink` is optional. When present, the endpoint links the
 *     new `WebAccount` to an *existing* `User` row identified by that
 *     Telegram id (the user landed in the bot first, then opened the Mini
 *     App and registered credentials). When absent, a brand-new `User`
 *     row is created from scratch (web-first sign-up).
 *   - `email` is optional and only used for password recovery — TG-linked
 *     users can recover via the bot too.
 *
 * Login policy: see `loginPolicy` in `auth/utils/login-policy.util.ts`.
 * Password is sent as plain text over the JWT-authenticated internal API
 * (in the same Docker network); admin hashes it with scrypt.
 */
export class WebAuthRegisterDto {
  @IsString()
  @Length(3, 64)
  @Matches(/^[A-Za-z0-9._-]+$/, {
    message: 'login may contain only letters, digits, dot, underscore and hyphen',
  })
  public readonly login!: string;

  @IsString()
  @Length(8, 256)
  public readonly password!: string;

  @IsOptional()
  @IsEmail()
  public readonly email?: string;

  @IsOptional()
  @IsString()
  @Matches(/^\d{1,19}$/, { message: 'telegramIdToLink must be a positive numeric string up to 19 digits' })
  public readonly telegramIdToLink?: string;

  /**
   * Optional referral code captured from the invite link
   * (`/register?ref=<code>`). The code is the referrer's reiwa_id (CUID),
   * telegramId, username, or referralCode. When present and resolvable, the
   * new user is attached as a referral of that referrer.
   */
  @IsOptional()
  @IsString()
  @Length(1, 64)
  public readonly referralCode?: string;
}
